### ISSUE TITLE
Unable to access dev.magento.com or 192.168.200.50

### ISSUE THREAD

**Issue by ALGilDiaz** [zepgram/magento2-fast-vm#107]
Everything has been installed without problems, and I'm able to reach:

http://192.168.60.0/

However, when I try to access Magento itself I always get a timeout. Vagrant's log does not show any attempt on connecting (/var/log/nginx/magento.access.log is empty). Pinging from the host gives me 100% loss. Either I missed something or the instructions missed a step.

This is my C:\Windows\System32\drivers\etc\hosts :

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#   127.0.0.1       localhost
#   ::1             localhost
192.168.200.50 dev.magento.com

```

This is my config.yaml:

```
vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.60.0'
  host_name: 'zepgram'
  memory: '4096'
  cpus: '1'
  mount: 'nfs'
  path: 'root'
  provision: 'all'
composer:
  username: 'redacted'
  password: 'redacted'
git:
  name: 'John Doe'
  email: 'john@doe.com'
  host: 'github.com'
  repository: 'ssh://git@github.com:project-name.git'
magento:
  url: 'dev.magento.com'
  source: 'composer'
  edition: 'community'
  version: '2.4.5'
  php_version: 'default'
  sample: 'true'
  mode: 'developer'
  currency: 'EUR'
  language: 'en_US'
  time_zone: 'America/New_York'
  crypt_key: ''
```
