### ISSUE TITLE
Problem Installing 

### ISSUE THREAD

**Issue by homerjsim** [zepgram/magento2-fast-vm#60]
Hello,

I am trying to install the VM. The vagrant up commands runs for some time and then I get these error messages at the end:

```
....
zepgram: Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
    zepgram: Package zendframework/zend-json is abandoned, you should avoid using it. Use laminas/laminas-json instead.
    zepgram: Package zendframework/zend-view is abandoned, you should avoid using it. Use laminas/laminas-view instead.
    zepgram: Package zendframework/zend-text is abandoned, you should avoid using it. Use laminas/laminas-text instead.
    zepgram: Package zendframework/zend-server is abandoned, you should avoid using it. Use laminas/laminas-server instead.
    zepgram: Package zendframework/zend-soap is abandoned, you should avoid using it. Use laminas/laminas-soap instead.
    zepgram: Package zendframework/zend-serializer is abandoned, you should avoid using it. Use laminas/laminas-serializer instead.
    zepgram: Package zendframework/zend-config is abandoned, you should avoid using it. Use laminas/laminas-config instead.
    zepgram: Package zendframework/zend-modulemanager is abandoned, you should avoid using it. Use laminas/laminas-modulemanager instead.
    zepgram: Package zendframework/zend-log is abandoned, you should avoid using it. Use laminas/laminas-log instead.
    zepgram: Package zendframework/zend-i18n is abandoned, you should avoid using it. Use laminas/laminas-i18n instead.
    zepgram: Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
    zepgram: Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
    zepgram: Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.
    zepgram:
    zepgram: Installation failed, reverting ./composer.json to its original content.
    zepgram:                                                                                                                                                                                                               
    zepgram:   [Composer\Repository\InvalidRepositoryException]                                                                                                                                                            
    zepgram:   Invalid repository data in /home/vagrant/magento/vendor/composer/installed.json, packages could not be loaded: [Seld\JsonLint\ParsingException] "/home/vagrant/magento/vendor/composer/installed.json" does not contain valid JSON
    zepgram:   Parse error on line 1:                                                                                                                                                                                      
    zepgram:                                                                                                                                                                                                               
    zepgram:   ^                                                                                                                                                                                                           
    zepgram:   Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['                                                                                                                                      
    zepgram:                                                                                                                                                                                                               
    zepgram: require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
    zepgram:                                                                                                                                                                                                               
    zepgram:   [Composer\Repository\InvalidRepositoryException]                                                                                                                                                            
    zepgram:   Invalid repository data in /home/vagrant/magento/vendor/composer/installed.json, packages could not be loaded: [Seld\JsonLint\ParsingException] "/home/vagrant/magento/vendor/composer/installed.json" does not contain valid JSON
    zepgram:   Parse error on line 1:                                                                                                                                                                                      
    zepgram:                                                                                                                                                                                                               
    zepgram:   ^                                                                                                                                                                                                           
    zepgram:   Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['                                                                                                                                      
    zepgram:                                                                                                                                                                                                               
    zepgram: chmod:
    zepgram: cannot access '/home/vagrant/magento/bin/magento'
    zepgram: : No such file or directory
    zepgram: sudo
    zepgram: :
    zepgram: /home/vagrant/magento/bin/magento: command not found
    zepgram: sudo
    zepgram: :
    zepgram: /home/vagrant/magento/bin/magento: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Any ideas?
