### ISSUE TITLE
Cannot authenticate with magento repo using composer?

### ISSUE THREAD

**Issue by ipkpjersi** [zepgram/magento2-fast-vm#73]
Hello,

I am using Ubuntu 18.04 with PHP 7.4 and trying to use this repo to install Magento 2.4.

I seem to get an error when trying to authenticate with the magento repo using composer:
![](https://i.imgur.com/pZRHSGD.png)

However, I have entered my magento credentials in config.yaml and the magento credentials I am using work for accessing www.magentocommerce.com/products/downloads/info/help since it does not give me a 401 Unauthorized error:
![](https://i.imgur.com/cyFX8NA.png)

Any suggestions?

Here is my config.yaml (I also had problems with it getting stuck on NFS mount step so I am trying rsync instead):
```yaml
vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.200.50'
  host_name: 'zepgram'
  memory: '4096'
  cpus: '1'
  mount: 'rsync'
  path: 'root'
  provision: 'all'
composer:
  username: 'MAG#HERE'
  password: 'CORRECTKEYHERE'
git:
  name: 'John Doe'
  email: 'john@doe.com'
  host: 'github.com'
  repository: 'ssh://git@github.com:project-name.git'
magento:
  url: 'dev.magento.com'
  source: 'composer'
  edition: 'community'
  version: '2.4.0'
  php_version: 'default'
  sample: 'true'
  mode: 'developer'
  currency: 'USD'
  language: 'en_US'
  time_zone: 'America/New_York'
  crypt_key: ''
```
